# Generated by Django 2.2.5 on 2019-10-24 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VitalSigns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vitals', models.CharField(max_length=100)),
                ('vitals1', models.CharField(max_length=100)),
                ('vitals2', models.CharField(max_length=100)),
            ],
        ),
    ]
